[package]
name = "oysterpack"
version = "0.1.0"
authors = ["Alfio Zappala <oysterpack2016@gmail.com>"]
description = "OysterPack Rust Platform"
license = "Apache-2.0"
repository = "https://github.com/oysterpack/oysterpack"
homepage = "https://github.com/oysterpack/oysterpack"

[dependencies]

[workspace]

[profile.release]
debug = true
lto = true
