[package]
name = "oysterpack_built"
version = "0.2.2"
authors = ["Alfio Zappala <oysterpack.inc@gmail.com>"]
description = "OysterPack Built"
license = "MIT/Apache-2.0"
repository = "https://github.com/oysterpack/oysterpack"
homepage = "https://github.com/oysterpack/oysterpack/tree/master/oysterpack-built"
documentation = "https://docs.rs/oysterpack_built"
readme = "README.md"
build = "build.rs"

[dependencies]
built = "0.3"

[dev-dependencies]
version-sync = "0.5"

[build-dependencies]
built = "0.3"

[badges]
