[package]
name = "oysterpack_built"
version = "0.1.0"
authors = ["Alfio Zappala <oysterpack.inc@gmail.com>"]
description = "OysterPack Built"
license = "MIT/Apache-2.0"
repository = "https://github.com/oysterpack/oysterpack"
homepage = "https://github.com/oysterpack/oysterpack"
readme = "README.md"
build = "build.rs"

[dependencies]
built = "0.3"

[dev-dependencies]
version-sync = "0.5"
chrono = "0.4"
semver = "0.9"

[build-dependencies]
built = "0.3"

[badges]
