[package]
name = "oysterpack_log"
version = "0.1.0"
authors = ["Alfio Zappala <oysterpack.inc@gmail.com>"]
description = "Standardizes logging for the OysterPack platform"
license = "MIT/Apache-2.0"
repository = "https://github.com/oysterpack/oysterpack"
homepage = "https://github.com/oysterpack/oysterpack/tree/master/oysterpack-log"
documentation = "https://docs.rs/oysterpack_log"
readme = "README.md"
keywords = ["log"]

[dependencies]
oysterpack_macros = {version = "0.1.0", path = "../oysterpack-macros"}

log = {version = "0.4", features = ["serde"]}
fern = {version = "0.5"}
chrono = { version = "0.4", features = ["serde"]}

serde = "1"
serde_derive = "1"

[dev-dependencies]
oysterpack_testing = {version = "0.1.0", path = "../oysterpack-testing" }
version-sync = "0.5"
serde_json = "1"

[badges]
maintenance = {status = "actively-developed"}
