[package]
name = "oysterpack_actors"
version = "0.1.0" # remember to update html_root_url
authors = ["Alfio Zappala <oysterpack.inc@gmail.com>"]
description = "OysterPack Actors"
license = "MIT OR Apache-2.0"
repository = "https://github.com/oysterpack/oysterpack"
homepage = "https://github.com/oysterpack/oysterpack"
readme = "README.md"

[dependencies]
actix = "0.5.5"
tokio = "0.1.5"
futures = "0.1"

# serde serializers
serde_cbor = "0.8.2"
serde_json = "1.0.13"
bincode = "1.0.0"
rmp-serde = "0.13.7"

oysterpack_id = {path = "../oysterpack-id", version = "0.1.0"}
oysterpack_platform = {path = "../oysterpack-platform", version = "0.1.0"}

[dev-dependencies]
version-sync = "0.5"

[profile.release]
debug = true
lto = true

[badges]
maintenance = { status = "actively-developed" }
