[package]
name = "oysterpack_lib_template"
version = "0.1.0"
authors = ["Alfio Zappala <oysterpack.inc@gmail.com>"]
description = "OysterPack XXX"
license = "MIT/Apache-2.0"
repository = "https://github.com/oysterpack/oysterpack"
homepage = "https://github.com/oysterpack/oysterpack"
readme = "README.md"
build = "build.rs"

[dependencies]
built = "0.3"

[dev-dependencies]
version-sync = "0.5"

[build-dependencies]
oysterpack_built = {path = "../oysterpack-built", version = "0.1"}

[badges]