[package]
name = "oysterpack_core"
version = "0.1.0"
authors = ["Alfio Zappala <oysterpack.inc@gmail.com>"]
description = "OysterPack Core"
license = "MIT/Apache-2.0"
repository = "https://github.com/oysterpack/oysterpack"
homepage = "https://github.com/oysterpack/oysterpack"
readme = "README.md"
build = "build.rs"

[dependencies]
log = "0.4"

crossbeam-channel = "0.2"
rayon = "1"
tokio = "0.1"

chrono = { version = "0.4", features = ["serde", "time"] }
rusty_ulid = "0.5"
lazy_static = "1"
failure = "0.1.2"
failure_derive = "0.1.2"
semver = "0.9"
built = "0.3"

serde = "1"
serde_derive = "1"
erased-serde = "0.3"
serde_json = "1"

[dev-dependencies]
version-sync = "0.5"
fern = "0.5"

[build-dependencies]
oysterpack_built = {path = "../oysterpack-built", version = "0.1"}

[badges]
maintenance = { status = "actively-developed" }
