[package]
name = "oysterpack-core"
version = "0.1.0"
authors = ["Alfio Zappala <oysterpack.inc@gmail.com>"]

[dependencies]
uuid = { version = "0.6", features = ["v4","v5","serde"] }
rand = "0.4.2"

[dev-dependencies]
version-sync = "0.5"