[package]
name = "oysterpack_core"
version = "0.1.0"
authors = ["Alfio Zappala <oysterpack.inc@gmail.com>"]
description = "OysterPack Core"
license = "MIT/Apache-2.0"
repository = "https://github.com/oysterpack/oysterpack"
homepage = "https://github.com/oysterpack/oysterpack/tree/master/oysterpack-core"
documentation = "https://docs.rs/oysterpack_core"
readme = "README.md"
build = "build.rs"

[dependencies]
oysterpack_built_mod = {path = "../oysterpack-built-mod"}
oysterpack_uid = {path = "../oysterpack-uid"}
log = "0.4"
chrono = { version = "0.4", features = ["serde", "time"] }
lazy_static = "1"

crossbeam-channel = "0.2"
rayon = "1"
tokio = "0.1"

rusty_ulid = "0.5"
failure = "0.1.2"
failure_derive = "0.1.2"
semver = "0.9"

serde = "1"
serde_derive = "1"
erased-serde = "0.3"
serde_json = "1"

[dev-dependencies]
version-sync = "0.5"
fern = "0.5"

[build-dependencies]
oysterpack_built = {path = "../oysterpack-built"}

[badges]
maintenance = { status = "actively-developed" }
