[package]
name = "oysterpack-sandbox"
version = "0.1.0"
authors = ["Alfio Zappala <oysterpack.inc@gmail.com>"]

[dependencies]
juniper = {version = "0.9", features = ["chrono", "serde_json", "uuid", "url"]}
